### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'path')

### ISSUE THREAD

**Issue by ofalvai** [FlorianWoelki/obsidian-iconize#501]
**Describe the bug**

Whenever I open a new empty tab, the following error is logged to the console:

```
app.js:1 Uncaught TypeError: Cannot read properties of null (reading 'path')
    at eval (plugin:obsidian-icon-folder:6297:50)
    at e.tryTrigger (app.js:1:723011)
    at e.trigger (app.js:1:722944)
    at t.trigger (app.js:1:2280272)
    at t.activeLeafEvents (app.js:1:2266073)
    at l (app.js:1:522835)
    at c (app.js:1:522951)
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by FlorianWoelki** [comment]
Please be more descriptive in the individual steps you've taken, so that I can reproduce this issue.
